<?php

    $Smileys = array(
    ':angry:'      => 'angry.gif',
    ':-D'          => 'biggrin.gif',
    ':|'           => 'blank.gif',
    ':blush:'      => 'blush.gif',
    ':cool:'       => 'cool.gif',
    ':crying:'     => 'crying.gif',
    '&gt;.&gt;'    => 'eyesright.gif',
    ':frown:'      => 'frown.gif',
    ':P'           => 'tongue.gif',
    ':wave:'       => 'wave.gif',
    ';-)'          => 'wink.gif',
    ':creepy:'     => 'creepy.gif',
    ':worried:'    => 'worried.gif',
    ':wtf:'        => 'wtf.gif',
    ':wub:'        => 'wub.gif',
    '&lt;3'        => 'heart.gif',
    ':unsure:'     => 'hmm.gif',
    ':lol:'        => 'laughing.gif',
    ':ninja:'      => 'ninja.gif',
    ':no:'         => 'no.gif',
    ':nod:'        => 'nod.gif',
    ':ohno:'       => 'ohnoes.gif',
    ':omg:'        => 'omg.gif',
    ':o'           => 'ohshit.gif',
    ':paddle:'     => 'paddle.gif',
    ':('           => 'sad.gif',
    ':shifty:'     => 'shifty.gif',
    ':sick:'       => 'sick.gif',
    ':)'           => 'smile.gif',
	':lovenbl:'    => 'lovenbl.gif',
    ':sorry:'      => 'sorry.gif',
    ':thanks:'     => 'thanks.gif',
    );
