<?php
$Toolbox = [
#   [Tool Name]                    [tools.php?action=???]  [Required Permission]

    ['Articles',                   'articles',             'admin_manage_articles'      ],
    ['Automatic Awards',           'awards_auto',          'site_manage_awards'         ],
    ['Automatic Banners',          'automatic_banners',    'admin_imagehosts'           ],
    ['Automatic Codecs',           'automatic_codecs',     'admin_manage_parser'        ],
    ['Automatic Parser',           'automatic_parser',     'admin_manage_parser'        ],
    ['Badges',                     'badges_list',          'site_manage_badges'         ],
    ['Bonus Shop',                 'shop_list',            'site_manage_shop'           ],
    ['Categories',                 'categories',           'admin_manage_categories'    ],
    ['Client Blacklist',           'client_blacklist',     'admin_whitelist'            ],
    ['Do not upload list',         'dnu',                  'admin_dnu'                  ],
    ['Email Blacklist',            'email_blacklist',      'admin_email_blacklist'      ],
    ['Featured Show',              'featured_show',        'admin_manage_networks'      ],
    ['Forums',                     'forum',                'admin_manage_forums'        ],
    ['Imagehost Whitelist',        'imghost_whitelist',    'admin_imagehosts'           ],
    ['IP Bans',                    'ip_ban',               'admin_manage_ipbans'        ],
    ['Login Watch',                'login_watch',          'admin_login_watch'          ],
    ['Manage freeleech tokens',    'tokens',               'users_mod'                  ],
    ['Manage invites',             'invites',              'users_mod'                  ],
    ['Marked for Deletion',        'marked_for_deletion',  'torrents_review'            ],
    ['MFD Reasons',                'reasons',              'admin_manage_reasons'       ],
    ['Misc Fixers',                'miscfixers',           'admin_manage_networks'      ],
    ['Networks',                   'networks',             'admin_manage_networks'      ],
    ['News',                       'news',                 'admin_manage_news'          ],
    ['Official Synonyms Manager',  'official_synonyms',    'site_convert_tags'          ],
    ['Official Tags Manager',      'official_tags',        'site_manage_tags'           ],
    ['Premiers',                   'premiers',             'admin_manage_networks'      ],
    ['Recent Comments',            'allcomments',          'users_mod'                  ],
    ['Shows',                      'shows',                'admin_manage_networks'      ],
    ['Site Languages',             'languages',            'admin_manage_languages'     ],
    ['Site Options',               'site_options',         'admin_manage_site_options'  ],
    ['Speed Cheats',               'speed_cheats',         'users_manage_cheats'        ],
    ['Speed Reports',              'speed_records',        'users_manage_cheats'        ],
    ['Tag Exceptions Manager',     'tags_exceptions',      'site_manage_tags'           ],
    ['User Classes',               'permissions',          'admin_manage_permissions'   ]
];
